FROM php:7.2.24-apache

# timezone
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# proxy
ARG HTTP_PROXY="http://10.166.133.81:3128"
ARG NO_PROXY="localhost, 127.0.0.0/8, ::1, 10.0.0.0/8, *.eb.mil.br"
ENV HTTPS_PROXY ${HTTP_PROXY}
ENV HTTP_PROXY ${HTTP_PROXY}
ENV FTP_PROXY ${HTTP_PROXY}
RUN echo "Acquire::https::Proxy \"$HTTP_PROXY\";" >> /etc/apt/apt.conf
RUN echo "Acquire::http::Proxy \"$HTTP_PROXY\";" >> /etc/apt/apt.conf
RUN echo "Acquire::ftp::Proxy \"$HTTP_PROXY\";" >> /etc/apt/apt.conf
RUN pear config-set http_proxy ${HTTP_PROXY}

# update and instalations
RUN apt update  && apt upgrade -y

# configure php
COPY conf.d/php.ini "${PHP_INI_DIR}/conf.d/my-php.ini"

# install xdebug
RUN yes | pecl install xdebug && docker-php-ext-enable xdebug
COPY conf.d/xdebug.ini "${PHP_INI_DIR}/conf.d"

# install php extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions @fix_letsencrypt && \
    install-php-extensions pdo_pgsql pgsql pdo_mysql mysqli\
    bcmath bz2 curl intl gd mbstring xml soap zip

RUN chmod -R 777 /var/www/html 



