version: '3.9'

services:
  web:
    build: .
    container_name: apache_container
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - db      
    networks:
      - my-network

  db:
    image: postgres:10
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
        - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network: