version: '3.7'
services:
  php-apache-xdebug:
    container_name: xdebug-php
    build: 
      context: ./docker/php/
    restart: always
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/log:/tmp/xdebug
    depends_on:
      - db   
    networks:
      - my-network

  db:
    image: postgres:10
    container_name: postgres_container
    environment:
      POSTGRES_USER: doc
      POSTGRES_PASSWORD: d0c3b
      POSTGRES_DB: sioc-leandro
    volumes:
        - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network: